### PR TITLE
feat: Add LambdaTest support to manage script

### PR DESCRIPTION
**Pull request by fc-santos**
## New Features ##

* Added script for uploading app to LambdaTest
* Added new device service handler for LambdaTest
* Added new json config for LambdaTest (Android & iOS) 

### Important ###

LambdaTest only supports at the moment [camera image injection](https://www.lambdatest.com/support/docs/camera-image-injection/). Biometrics is not a feature that this platform can offer for now.

Also, for iOS the minimum platformVersion they have for real devices is 14, which needs to be considered since the wallet app has the target configured for minimum deployments at 11.0.

### CODE REVIEW

**Comment by nodlesh** [comment]
This is great! Thank you for the submission. I think you might be out of date with main (I have put a change in on requirements.txt to pin Appium because of a recent release problem). If you can merge with main, I'll approve this and merge it. Thanks again!

**Review by nodlesh — APPROVED** [review]
Awesome thanks!

**Comment by nodlesh** [comment]
Just merged my local branch with your changes. I don't set `DEVICE_PLATFORM` env var. Is this needed? I see it being retrieved in environment.py but I don't see it being used anywhere? 
```
# Get the Device Platform
device_platform_name = config('DEVICE_PLATFORM')
```

**Comment by fc-santos** [comment]
It's for eventually use to set the language of the device. In Android to set the language of the app in automation you need to pass : 

```javascript
{
   "language": "en",  // or fr
   "locale": "CA",
}
```

While in IOS, you pass only the locale:

```javascript
{
   "locale": "en_CA" // or fr_CA
}
```

It could be part of the solution to #53 by setting proper capability.

**Comment by nodlesh** [comment]
It is ok if I remove it(or comment out) from environment.py in the next PR merge I make? If it isn't being used yet then it is going to get in the way of others especially if they don't know what it is for. Also "DEVICE_PLATFORM" doesn't hint at language, so maybe another name would be clearer? 
We can mention this solution in #53 if the intent is to solve that problem. However, env vars are usually set at the beginning of a run, #53 suggests changing these settings between tests in the middle of the same run.

**Comment by fc-santos** [comment]
Sure, no problem.

**Pull request merged**
