### PR TITLE
Henri/back2py

### PR DESCRIPTION
**Pull request by Vanderscycle**
added a .gitignore and corrected typos

### CODE REVIEW

**Review by nodlesh — DISMISSED** [review]
👍

**Comment by nodlesh** [comment]
@Vanderscycle You will need to fix the DCO. You need to sign-off all commits to merge into this repo. 
In the git workflow it says this, 
`git commit -m "this is my commit message" --signoff`
Thanks.

**Comment by Vanderscycle** [comment]
Through gpg correct?

**Comment by swcurran** [comment]
No -- it's not a gpg key that is needed -- just the signoff (-s is needed, not -S).  See DCO - Developer Certificate of Origin - https://github.com/apps/dco -- you can also click the details link beside the DCO fail.

It's a pain if you miss it -- might be easier to redo :-(.  Depends on your git guru-ness.

**Comment by Vanderscycle** [comment]
@swcurran @nodlesh I'll squash the branch, fix my gpg and try the``` git commit -ms 'commit msg' ```

**Pull request closed without merging**
