### PR TITLE
Fix for feature "Scan QR code to recieve a credential offer" in connect.feature

### PR DESCRIPTION
**Pull request by geethutnair94**
**Error existed**
Not able to find Scan button as the Biometric page was not handled 
image

**Changes made**

> Added line to use biometrics
> Changed the way to find Allow button on IOS devices

Test Result
image

### CODE REVIEW

**Comment by nodlesh** [comment]
Good first submission!  I'm curious if the changing of the way to find the Allow button worked better for you? Those methods for clicking the allow we tested to see which one is faster, and I'm my tests the `WaitCondition.PRESENCE_OF_ELEMENT_LOCATED` seemed to be the fastest. For some reason clicking on Allow on iOS takes a really long time. If you feel that this method is more reliable and faster, then we can merge it and try it out?

FYI, any tests that have a tag of @wip are work in progress tests. We either will get to them at some point or we've decided that we don't need to run them anymore. This one T001-Connection was turned off because all of the other tests connect anyway so it is being tested in a more complete scenario. However, we could turn this one connection test back on. To do that you need to remove the @wip tag from that test in the feature file.

**Comment by geethutnair94** [comment]
Thanks @nodlesh .
I completely understand that @wip tags now.
As requested I removed the @wip tag for that passing test.

When I use PRESENCE_OF_ELEMENT_LOCATED  it session out and fails the scenario. It could not find the Allow button, so by referring to other functions I tried ELEMENT_TO_BE_CLICKABLE, and that worked as expected.

**Comment by nodlesh** [comment]
Thanks Geethu,  could you also make sure it works with the latest in main?

**Review by nodlesh — APPROVED** [review]
Awesome! Thanks.

**Pull request merged**
