### PR TITLE
Adding Silent Reporting Feature

### PR DESCRIPTION
**Pull request by pradeepp88**
This PR adds an argument to the send_results and send_results_secure script in allure to generate the report silently without getting a response. This is to avoid the gateway timeout error when generating large reports when the allure server is hosted in a cloud environment secured by modern CDNs.

### CODE REVIEW

**Comment by nodlesh** [comment]
@pradeepp88 You will need to sign your commits. Otherwise the DCO check will fail as it has in this PR. This is required for Hyperledger repos. Thanks.

**Comment by nodlesh** [comment]
Sorry, I didn't notice this PR was still in draft. I'll hold off reviewing.

**Comment by pradeepp88** [comment]
> @pradeepp88 You will need to sign your commits. Otherwise the DCO check will fail as it has in this PR. This is required for Hyperledger repos. Thanks.

@nodlesh I have signed off the previous commits. I still need to add one commit with the modified shell scripts. I will do it and complete the PR.

**Review by nodlesh — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
